### ISSUE TITLE
allow specifying required=true for `arg`

### ISSUE THREAD

**Issue by brentp** [iffy/nim-argparse#15]
this would be nice to avoid checking e.g.
```
if opts.myargs == "":
    quit p.help & "\nmyarg is required"
```
I guess this could also be via `nargs=1`, but that does not currently give an error if no arguments are given.

**Comment by iffy** [comment]
`arg` is meant to mean "required" so it's a bug that a UsageError is not thrown.  Does this correctly test the behavior you'd expect? (it currently fails, so I'm guessing so):

```nim
  test "args are required":
    var p = newParser("someprog"):
      arg("name")
    expect UsageError:
      discard p.parse(shlex"")
```

**Comment by brentp** [comment]
ok. good. I thought it was odd behavior. Yes, that looks like it should test the problem I am seeing.
