### ISSUE TITLE
Skip main run path if subcommands are present

### ISSUE THREAD

**Issue by reesmichael1** [iffy/nim-argparse#27]
First off, thanks for a great library!

When using `parser.run`, I would like to be able to not run the main `run` block when a subcommand is called. For example, in the following setup:

```
import argparse

var p = newParser("demo"):
  command("subcommand"):
    run:
      echo "in subcommand"
  run:
    echo "in main"

p.run(@["subcommand"])
p.run(@[])
```

I would like there to be a way for the output to be 

```
in subcommand
in main
```

(Currently, it shows `in main` / `in subcommand` / `in main`.)

Is this currently possible, or would it be possible to add?

Thanks!

**Comment by iffy** [comment]
That sounds like a reasonable request to me.  What should the syntax be?

```nim
command("subcommand"):
  run:
    echo "in subcommand"
run:
  if opts.subcommand == "":
    echo "in main"
```

Or something else?

**Comment by reesmichael1** [comment]
That seems like a good approach to me (and was the first thing I tried when I was trying to find a way to do this). Another option could be to add another `proc` to the command block, like:

```
command("subcommand"):
  exclusive() # probably with a better name
  run:
    echo "in subcommand"
```

But I think your suggestion is more natural.

**Comment by reesmichael1** [comment]
Thanks a bunch! This [is working perfectly](https://git.sr.ht/~reesmichael1/roman/commit/26fc9a25b75d57cd966d140cdcbff27dec0531cc).

Again, thank you for such a well done library.
