### ISSUE TITLE
IndexError when option is missing argument

### ISSUE THREAD

**Issue by SoftwareApe** [iffy/nim-argparse#29]
# Behavior

You specify a parser with an option argument. E.g.

```nim
var argparser = newParser("my prog"):
    option("-f", "--file", multiple=false, help="File to process")
run:
    ...
```

If you call this program with
```nim
argparser.run(commandLineParams())
```

and then only supply e.g. the option "-f" you get an IndexError.

# Expected Behavior
Instead of an index error print a help message that the option is missing a value.

**Comment by iffy** [comment]
Fixed in v1.0.0
