### ISSUE TITLE
Required options

### ISSUE THREAD

**Issue by bluenote10** [iffy/nim-argparse#31]
Another feature that I'm missing (unless I'm missing something ;)) is to have `required` options. As far as I can see mandatory arguments are currently only possible as positional arguments. I often prefer options like `-i`/`--input`/`-o`/`--output`/`--important-param` over positional arguments for their explicitness and positional independence.

**Comment by iffy** [comment]
You're not missing anything :) Required options aren't implemented yet.  And I like using them too for the same reasons

**Comment by iffy** [comment]
Finally, this is implemented!
