### ISSUE TITLE
group order

### ISSUE THREAD

**Issue by danielecook** [iffy/nim-argparse#36]
Is there a way to set the ordering of grouped commands?

I cannot figure out how the ordering of groups is determined.

Thanks

**Comment by iffy** [comment]
It looks like currently ordering is not defined.  It's whatever `Table.keys()` order is.  But it looks like if we switched to `OrderedTable` it would at least be deterministic and probably be in the order you define them in.  Would that work?

**Comment by danielecook** [comment]
I think that'll work! Thanks
