### ISSUE TITLE
With parse(), no way to print help for subcommand

### ISSUE THREAD

**Issue by iffy** [iffy/nim-argparse#62]
```nim
var p = newParser:
  command "foo":
    flag("-a")
  command "bar":
    flag("-b")
try:
  var opts = p.parse(@["foo", "--help"])
except ShortCircuit as e:
  if e.flag == "argparse_help":
    echo p.help # how do I get p.fooParser.help or know that they passed in foo?
```

**Comment by ghost** [comment]
This has been really bugging me out, just asking for status on this issue please. If it is not gonna get fixed anytime soon, please let me know

**Comment by iffy** [comment]
Turns out it was easy -- thanks for letting me know it was bugging you.

**Comment by iffy** [comment]
There's now a `.help` field on the `ShortCircuit` error object so this should work:

```nim
try:
  var opts = p.parse()
except ShortCircuit as err:
  if err.flag == "argparse_help":
    echo err.help
```

https://github.com/iffy/nim-argparse#parse

**Comment by ghost** [comment]
OMG! You are a legend! Thank you so much

**Comment by yaroslav-gwit** [comment]
Just wanted to say thank you. Before you implemented the change, I had to use this monkey patch 🙈:

```nim
if opts.command == "vm":
    var vmList = vmList()
else:
    echo execCmdEx(os.getAppFilename() & " vm --help")[0].strip
```

Essentially executing a shell sub-command, and calling `--help` on it.
