### ISSUE TITLE
Don't convert option values to string

### ISSUE THREAD

**Issue by floscr** [iffy/nim-argparse#68]
Values for options get automatically converted to `""` even if the user has not passed any value,
this makes it impossible to detect if the user has passed an empty string to the cli.

It would be neat to get a way to access the original `Option` so we can be more explicit.

Something like this

```nim
var p = newParser:
  command("command"):
    option("--foo")
    run:
      assert: opts.fooOpt == none[string]
```

**Comment by iffy** [comment]
I like the idea of adding an `Opt` (or `_opt`) suffix to the variable name to preserve backward compatibility.

**Comment by floscr** [comment]
Awesome, thank you! :raised_hands:
