### ISSUE TITLE
ENH: allow repeated options.

### ISSUE THREAD

**Issue by brentp** [iffy/nim-argparse#7]
thanks for the library. it looks close to what I need and I'm trying to get it going in one of my projects.
however, I'd like to be able to do something like:
```
    option("-f", "--field", help="field(s) to use for value", nargs=-1)
```

and then on the command-line, the user could specify
```
  -f abc -f def -f xyz
```
and  the parsed result would be `@["abc", "def", "xyz"]`

is something like this possible? I need this independently from `arg` because I have mutliple options that allow variable number of arguments.

**Comment by iffy** [comment]
Yeah, that should be possible (it's already available for positional args).  I'm not sure when I'll get around to it, but if you're feeling adventurous, I'd take a PR :)  Be warned that this is the first macro-using Nim code I wrote so it's a little hairy.  If not, I'll get to it sometime soon.

**Comment by brentp** [comment]
that would be great.
before opening I had a look at the code and thought I might make my first foray into macro-ing but I didn't get far.
