### ISSUE TITLE
Passing an option value without `=` breaks parsing multiple arguments

### ISSUE THREAD

**Issue by ZoomRmc** [iffy/nim-argparse#77]
```nim
import argparse

when isMainModule:
  var p = newParser:
    option("-n", "--number", default=some("0"))
    arg("inputA", nargs = 1)
    arg("inputB", nargs = 1)

  try:
    let opts = p.parse(@["-n 2", "A", "B"])
  except UsageError:
    stderr.writeLine getCurrentExceptionMsg()
    quit(1)
```

Output: `Unknown argument(s): B`
Changing `"-n 2"` to `"-n=2"` works as expected.

This passes, which is unexpected (and, IMO, broken):
```nim
import argparse

when isMainModule:
  var p = newParser:
    option("-n", "--number", default=some("0"))
    arg("inputA", nargs = 1)
    arg("inputB", nargs = 1)
  let opts = p.parse(@["-n 2", "A"])
  doAssert opts.number == "0"
  doAssert opts.inputA == "-n 2"
  doAssert opts.inputB == "A"
```

It looks like argparse can't parse a value for an option without `=`. The docs are not clear on the rules, the only mention of allowed format is in the table on the doc page: 
> `option(...)` option with argument (e.g. `--output foo`)

Which means passing whitespace delimited option values should work.

**Comment by iffy** [comment]
You would need to do `let opts = p.parse(@["-n", "2", "A"])` Does that work?

Edit to add: Doing `@["-n 2", "A"]` is equivalent to running the program from a shell like this: `> myprog '-n 2' A`

**Comment by ZoomRmc** [comment]
Yep, sorry for the bad issue.
Bitten by trying to apply a broken test before running the actual program to test manually. :D

The part on explicitly listing available value passing syntax still stands:
  - ✔️ `-x=n`
  - ✔️ `-x n`
  - ❌ `-x:n`
  - ❌ `-xn`
