### ISSUE TITLE
FR: Provide user-defined short-circuiting, (allows `--version`)

### ISSUE THREAD

**Issue by ZoomRmc** [iffy/nim-argparse#85]
A user defined error flag for short-circuiting, such as `"argparse_help"` would be nice, as it could allow react to a flag/command. Currently it looks like you can't ignore the absence of positional arguments and act on a flag, such as `-v`/`--version`.
At the very least a hardcoded "argparse_version" is enough to get by.

**Comment by iffy** [comment]
Does the `shortcircuit` arg to `flag` do what you want? https://github.com/iffy/nim-argparse/blob/master/src/argparse.nim#L143

If not, can you provide an example of how you'd like it to look?

**Comment by ZoomRmc** [comment]
Ouch, I'm so sorry, don't know how I missed it.
`flag("-v", "--version", help="Print version and exit"` and ` except ShortCircuit as err: (if err.flag == "version": echo versionConst`) completely covers it.
